# Generated by Django 5.0.1 on 2024-02-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="credentials",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
